"""RailMind AI Schemas Package."""
from backend.schemas.train import (
    TrainBase,
    TrainCreate,
    TrainUpdate,
    TrainResponse,
    TrainPositionUpdate,
    TrainListResponse,
    TrainFullGraph,
)
from backend.schemas.route import (
    RouteBase,
    RouteCreate,
    RouteResponse,
    RoutePathRequest,
    RoutePathResponse,
    RouteReservationRequest,
    RouteReservationResponse,
    RouteConflictReport,
)
from backend.schemas.platform import (
    PlatformBase,
    PlatformCreate,
    PlatformResponse,
    PlatformAllocationRequest,
    PlatformAllocationResponse,
    PlatformReleaseRequest,
    PlatformListResponse,
)
from backend.schemas.signal import (
    SignalBase,
    SignalCreate,
    SignalUpdate,
    SignalResponse,
    SignalSafetyRequest,
    SignalSafetyResponse,
    SignalListResponse,
)
from backend.schemas.event import (
    EventBase,
    EventCreate,
    EventResponse,
    EventFilterRequest,
    EventListResponse,
    EventStatsResponse,
)

__all__ = [
    "TrainBase",
    "TrainCreate",
    "TrainUpdate",
    "TrainResponse",
    "TrainPositionUpdate",
    "TrainListResponse",
    "TrainFullGraph",
    "RouteBase",
    "RouteCreate",
    "RouteResponse",
    "RoutePathRequest",
    "RoutePathResponse",
    "RouteReservationRequest",
    "RouteReservationResponse",
    "RouteConflictReport",
    "PlatformBase",
    "PlatformCreate",
    "PlatformResponse",
    "PlatformAllocationRequest",
    "PlatformAllocationResponse",
    "PlatformReleaseRequest",
    "PlatformListResponse",
    "SignalBase",
    "SignalCreate",
    "SignalUpdate",
    "SignalResponse",
    "SignalSafetyRequest",
    "SignalSafetyResponse",
    "SignalListResponse",
    "EventBase",
    "EventCreate",
    "EventResponse",
    "EventFilterRequest",
    "EventListResponse",
    "EventStatsResponse",
]